#%RAML 1.0 NamedExample
value:
  -
    id: 007
    firstName: John
    lastName: Doe
    address:  12 Avenue des Champs Elysées
    postal: 75000
    country:  France
    miles:  2
    creationDate: 2019-10-03T13:30:00.000Z